<a href="https://colab.research.google.com/github/dvvp/Genasys-300X-Data-Analysis/blob/main/Genasys_300X_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [182]:
import pandas as pd
import numpy as np
import os
import xlrd

In [183]:
dir = '/content/'

lst = []

for file in os.listdir(dir):
  if file.endswith(".xlsx"):
    lst.append(file.split("] ")[1])

# these are the different tests we have
wo_id = np.unique(lst).tolist()
wo_id

['Maximum Output (Wide-Off, Ch1) - PASSED.xlsx',
 'Maximum Output (Wide-Off, Ch2) - PASSED.xlsx',
 'SNR (Wide-Off, Ch1) - PASSED.xlsx',
 'SNR (Wide-Off, Ch2) - PASSED.xlsx',
 'Sensitivity (MP3 Input, Sound Projection Narrow, VB OFF, (Ch1) - PASSED.xlsx',
 'Sensitivity (MP3 Input, Sound Projection Narrow, VB ON, (Ch1) - PASSED.xlsx',
 'Sensitivity (MP3 Input, Sound Projection Wide, VB OFF, Ch1) - PASSED.xlsx',
 'Sensitivity (MP3 Input, Sound Projection Wide, VB OFF, Ch2) - PASSED.xlsx',
 'Sensitivity (MP3 Input, Sound Projection Wide, VB ON, Ch1) - PASSED.xlsx']

# Maximum Output (Wide-Off, Ch1)

In [184]:
created_final_df = False
for file in os.listdir(dir):
  if file.endswith(".xlsx"):
    if ('Maximum Output (Wide-Off, Ch1) - PASSED.xlsx' in file):
      df = pd.ExcelFile(dir + file).parse('FFT Spectrum')
      df = df.tail(df.shape[0] - 3)
      df.rename(columns = {"FFT Spectrum" : "X", "Unnamed: 1" : "Y"}, inplace = True)
      df = df.set_index("X")
      if not created_final_df:
        final_df = pd.DataFrame(df.index)
        final_df = final_df.set_index("X")
        created_final_df = True
      final_df = pd.concat([final_df, df], axis=1)

max = final_df.max(axis = 1)
min = final_df.min(axis = 1)
final_df = final_df.assign(MAX = max, MIN = min)
final_df = final_df.get(["MAX", "MIN"])
final_df

/usr/local/lib/python3.7/dist-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5047: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

                   MAX           MIN
X
19.042969     0.000079  5.320917e-06
20.507812     0.000061  9.053002e-06
21.972656     0.000059  1.086523e-05
23.437500     0.000088  7.888872e-06
24.902344     0.000127  4.857368e-06
...                ...           ...
19768.066406  0.000085  7.491006e-05
19920.410156  0.001363  4.955204e-07
19921.875000  0.000035  2.307890e-07
19923.339844  0.000024  2.135706e-05
19999.511719  0.015339  9.696543e-04

[2264 rows x 2 columns]

# Maximum Output (Wide-Off, Ch2)

In [185]:
created_final_df = False
for file in os.listdir(dir):
  if file.endswith(".xlsx"):
    if ("Maximum Output (Wide-Off, Ch2) - PASSED.xlsx" in file):
      df = pd.ExcelFile(dir + file).parse("FFT Spectrum")
      df = df.tail(df.shape[0] - 3)
      df.rename(columns = {"FFT Spectrum" : "X", "Unnamed: 1" :"Y"}, inplace = True)
      df = df.set_index("X")
      if not created_final_df:
        final_df = pd.DataFrame(df.index)
        final_df = final_df.set_index("X")
        created_final_df = True
      final_df = pd.concat([final_df, df], axis=1)

max = final_df.max(axis = 1)
min = final_df.min(axis = 1)
final_df = final_df.assign(MAX = max, MIN = min)
final_df = final_df.get(["MAX", "MIN"])
final_df

/usr/local/lib/python3.7/dist-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5047: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

                   MAX           MIN
X
19.042969     0.000098  6.117348e-06
20.507812     0.000191  7.098801e-06
21.972656     0.000210  3.361600e-06
23.437500     0.000228  5.430222e-06
24.902344     0.000171  6.079708e-06
...                ...           ...
19768.066406  0.000080  7.033404e-05
19920.410156  0.000098  1.317171e-06
19921.875000  0.000032  9.984518e-07
19923.339844  0.000029  2.467024e-05
19999.511719  0.013823  4.896563e-04

[2301 rows x 2 columns]

# SNR (Wide-Off, Ch1)

In [186]:
snr = []

created_final_df = False
for file in os.listdir(dir):
  if file.endswith(".xlsx"):
    if ("SNR (Wide-Off, Ch1) - PASSED.xlsx" in file):
        df = pd.ExcelFile(dir + file).parse("Signal to Noise Ratio")
        df = df.tail(df.shape[0] - 2)
        df.rename(columns = {"Signal to Noise Ratio" : "Channel", "Unnamed: 1" : "Signal to Noise Ratio", "Unnamed: 2" : "Lower Limit"}, inplace = True)
        df = df.drop(columns = "Unnamed: 3")
        df = df.set_index("Channel")
        if not created_final_df:
          final_df = pd.DataFrame({"Channel" : ["Ch1"]})
          final_df = final_df.set_index("Channel")
          created_final_df = True
        snr.append(df.get("Signal to Noise Ratio").max())

final_df = final_df.assign(MAX = [np.max(snr)], MIN = [np.min(snr)])
final_df

/usr/local/lib/python3.7/dist-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

               MAX        MIN
Channel
Ch1      86.766539  83.674726

# SNR (Wide-Off, Ch2)

In [187]:
snr = []

created_final_df = False
for file in os.listdir(dir):
  if file.endswith(".xlsx"):
    if ("SNR (Wide-Off, Ch2) - PASSED.xlsx" in file):
        df = pd.ExcelFile(dir + file).parse("Signal to Noise Ratio")
        df = df.tail(df.shape[0] - 2)
        df.rename(columns = {"Signal to Noise Ratio" : "Channel", "Unnamed: 1" : "Signal to Noise Ratio", "Unnamed: 2" : "Lower Limit"}, inplace = True)
        df = df.drop(columns = "Unnamed: 3")
        df = df.set_index("Channel")
        if not created_final_df:
          final_df = pd.DataFrame({"Channel" : ["Ch2"]})
          final_df = final_df.set_index("Channel")
          created_final_df = True
        snr.append(df.get("Signal to Noise Ratio").max())

final_df = final_df.assign(MAX = [np.max(snr)], MIN = [np.min(snr)])
final_df

/usr/local/lib/python3.7/dist-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

                MAX        MIN
Channel
Ch2      117.079287  83.890446

# Sensitivity (MP3 Input, Sound Projection Narrow, VB OFF, (Ch1)

In [188]:
created_final_df = False
for file in os.listdir(dir):
  if file.endswith(".xlsx"):
    if ("Sensitivity (MP3 Input, Sound Projection Narrow, VB OFF, (Ch1) - PASSED.xlsx" in file):
      df = pd.ExcelFile(dir + file).parse('RMS Level')
      df = df.tail(df.shape[0] - 3)
      df.rename(columns = {"RMS Level" : "X", "Unnamed: 1" : "Y"}, inplace = True)
      df = df.set_index("X")
      if not created_final_df:
        final_df = pd.DataFrame(df.index)
        final_df = final_df.set_index("X")
        created_final_df = True
      final_df = pd.concat([final_df, df], axis=1)

max = final_df.max(axis = 1)
min = final_df.min(axis = 1)
final_df = final_df.assign(MAX = max, MIN = min)
final_df = final_df.get(["MAX", "MIN"])
final_df

/usr/local/lib/python3.7/dist-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5047: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

                   MAX        MIN
X
199.675325   -1.188103 -11.081780
204.545455   -0.650373 -10.515544
209.415584   -0.132862  -9.973601
209.415584   -0.413043  -9.641644
214.285714    0.363686  -9.451720
...                ...        ...
9964.285714  17.931312   9.161316
9988.636364  17.911005   9.141139
9993.506494   9.538453   9.538453
9993.506494  17.907444   9.135600
9998.376623  17.904716   9.128201

[2220 rows x 2 columns]

# Sensitivity (MP3 Input, Sound Projection Narrow, VB ON, (Ch1)

In [189]:
created_final_df = False
for file in os.listdir(dir):
  if file.endswith(".xlsx"):
    if ("Sensitivity (MP3 Input, Sound Projection Narrow, VB ON, (Ch1) - PASSED.xlsx" in file):
      df = pd.ExcelFile(dir + file).parse('RMS Level')
      df = df.tail(df.shape[0] - 3)
      df.rename(columns = {"RMS Level" : "X", "Unnamed: 1" : "Y"}, inplace = True)
      df = df.set_index("X")
      if not created_final_df:
        final_df = pd.DataFrame(df.index)
        final_df = final_df.set_index("X")
        created_final_df = True
      final_df = pd.concat([final_df, df], axis=1)

max = final_df.max(axis = 1)
min = final_df.min(axis = 1)
final_df = final_df.assign(MAX = max, MIN = min)
final_df = final_df.get(["MAX", "MIN"])
final_df

/usr/local/lib/python3.7/dist-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

                   MAX        MIN
X
199.675325    5.796887   0.699160
204.545455    6.203455   1.115771
209.415584    6.595852   1.517504
209.415584    6.595213   1.794987
214.285714    6.972374   1.902883
...                ...        ...
9964.285714  20.910107  16.452609
9988.636364  20.893301  16.439592
9993.506494  16.707459  16.707459
9993.506494  20.890693  16.438428
9998.376623  20.890172  16.430786

[2219 rows x 2 columns]

# Sensitivity (MP3 Input, Sound Projection Wide, VB OFF, Ch1)

In [190]:
created_final_df = False
for file in os.listdir(dir):
  if file.endswith(".xlsx"):
    if ("Sensitivity (MP3 Input, Sound Projection Wide, VB OFF, Ch1) - PASSED.xlsx" in file):
      df = pd.ExcelFile(dir + file).parse('RMS Level')
      df = df.tail(df.shape[0] - 3)
      df.rename(columns = {"RMS Level" : "X", "Unnamed: 1" : "Y"}, inplace = True)
      df = df.set_index("X")
      if not created_final_df:
        final_df = pd.DataFrame(df.index)
        final_df = final_df.set_index("X")
        created_final_df = True
      final_df = pd.concat([final_df, df], axis=1)

max = final_df.max(axis = 1)
min = final_df.min(axis = 1)
final_df = final_df.assign(MAX = max, MIN = min)
final_df = final_df.get(["MAX", "MIN"])
final_df

/usr/local/lib/python3.7/dist-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5047: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

                   MAX       MIN
X
199.675325    8.945134 -1.220783
204.545455    9.404081 -0.719594
209.415584    9.841718 -0.238943
209.415584    9.100407  0.007357
214.285714   10.258365  0.217782
...                ...       ...
9964.285714  17.974875  9.191513
9988.636364  17.957988  9.165541
9993.506494  17.755432  9.161062
9993.506494  17.953799  9.219697
9998.376623  17.949390  9.162439

[2203 rows x 2 columns]

# Sensitivity (MP3 Input, Sound Projection Wide, VB OFF, Ch2)

In [191]:
created_final_df = False
for file in os.listdir(dir):
  if file.endswith(".xlsx"):
    if ("Sensitivity (MP3 Input, Sound Projection Wide, VB OFF, Ch2) - PASSED.xlsx" in file):
      df = pd.ExcelFile(dir + file).parse('RMS Level')
      df = df.tail(df.shape[0] - 3)
      df.rename(columns = {"RMS Level" : "X", "Unnamed: 1" : "Y"}, inplace = True)
      df = df.set_index("X")
      if not created_final_df:
        final_df = pd.DataFrame(df.index)
        final_df = final_df.set_index("X")
        created_final_df = True
      final_df = pd.concat([final_df, df], axis=1)

max = final_df.max(axis = 1)
min = final_df.min(axis = 1)
final_df = final_df.assign(MAX = max, MIN = min)
final_df = final_df.get(["MAX", "MIN"])
final_df

/usr/local/lib/python3.7/dist-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

                   MAX        MIN
X
199.675325    8.904436  -1.231188
204.545455    9.365211  -0.729437
209.415584    9.804351  -0.250060
209.415584    9.065330  -0.139279
214.285714   10.221914   0.208030
...                ...        ...
9988.636364  17.926303   9.176792
9993.506494  17.932689   9.664087
9993.506494  17.924406   9.172868
9998.376623  17.929985  17.929985
9998.376623  17.919591   9.167050

[2366 rows x 2 columns]

# Sensitivity (MP3 Input, Sound Projection Wide, VB ON, Ch1)

In [192]:
created_final_df = False
for file in os.listdir(dir):
  if file.endswith(".xlsx"):
    if ("Sensitivity (MP3 Input, Sound Projection Wide, VB ON, Ch1) - PASSED.xlsx" in file):
      df = pd.ExcelFile(dir + file).parse('RMS Level')
      df = df.tail(df.shape[0] - 3)
      df.rename(columns = {"RMS Level" : "X", "Unnamed: 1" : "Y"}, inplace = True)
      df = df.set_index("X")
      if not created_final_df:
        final_df = pd.DataFrame(df.index)
        final_df = final_df.set_index("X")
        created_final_df = True
      final_df = pd.concat([final_df, df], axis=1)

max = final_df.max(axis = 1)
min = final_df.min(axis = 1)
final_df = final_df.assign(MAX = max, MIN = min)
final_df = final_df.get(["MAX", "MIN"])
final_df

/usr/local/lib/python3.7/dist-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

                   MAX        MIN
X
199.675325   15.442275  10.550298
204.545455   15.765189  10.892610
209.415584   15.981964  11.219737
209.415584   16.073826  11.302337
214.285714   16.366979  11.531204
...                ...        ...
9988.636364  20.941618  16.474714
9993.506494  20.831559  16.679913
9993.506494  20.937787  16.480987
9998.376623  16.676083  16.676083
9998.376623  20.933170  16.482252

[2345 rows x 2 columns]